name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-outputs
        path: |
          app/build/outputs/apk
          app/build/reports
          !app/build/reports/tests
          app/build/test-results
          !app/build/test-results/testDebugUnitTest/binary
          !app/build/test-results/testReleaseUnitTest/binary
